# Generated by Django 4.1.5 on 2023-01-31 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_ride_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.vehicle'),
        ),
    ]
