# Generated by Django 4.1.5 on 2023-02-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='special_req',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='special_info',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ride',
            name='if_share',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='vehicleType',
            field=models.IntegerField(blank=True, choices=[(0, 'Sedan'), (1, 'SUV'), (2, 'Coupe'), (3, 'Hatchback'), (4, 'Mini van')], default=None, help_text='-Sedan: 4 door trunks, capacity: 4 <br/>        -SUV: Sport-Utility Vehicle, capacity: 5 <br/>        -Coupe: 2 door trunks, capacity: 2 <br/>        -Hatchback: Compact sedan, capacity: 4 <br/>        -Minivan: Trunks with large cargo area, capacity: 7 <br/>        * The capacity includes driver. '),
        ),
    ]
