# Generated by Django 4.1.5 on 2023-02-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_ride_special_req_vehicle_special_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicleType',
            field=models.IntegerField(choices=[(0, 'Not required'), (1, 'Sedan'), (2, 'SUV'), (3, 'Coupe'), (4, 'Hatchback'), (5, 'Mini van')], help_text='-Sedan: 4 door trunks, capacity: 4 <br/>        -SUV: Sport-Utility Vehicle, capacity: 5 <br/>        -Coupe: 2 door trunks, capacity: 2 <br/>        -Hatchback: Compact sedan, capacity: 4 <br/>        -Minivan: Trunks with large cargo area, capacity: 7 <br/>        * The capacity includes driver. '),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleType',
            field=models.IntegerField(choices=[(0, 'Not required'), (1, 'Sedan'), (2, 'SUV'), (3, 'Coupe'), (4, 'Hatchback'), (5, 'Mini van')], help_text='-Sedan: 4 door trunks, capacity: 4 <br/>        -SUV: Sport-Utility Vehicle, capacity: 5 <br/>        -Coupe: 2 door trunks, capacity: 2 <br/>        -Hatchback: Compact sedan, capacity: 4 <br/>        -Minivan: Trunks with large cargo area, capacity: 7 <br/>        * The capacity includes driver. '),
        ),
    ]
